### ISSUE TITLE
我也是win10的，可是没执行成功

### ISSUE THREAD

**Issue by soipray** [strivexjun/MemoryModulePP#1]
FindPattern 函数的原理是什么

**Comment by soipray** [comment]
My system is win10,too.
But exe  abnormality because pfnRtlInsertInvertedFunctionTable_Win8_Win10 is null，
how does function FindPattern works？

**Comment by soipray** [comment]
win10 version 1803

**Comment by strivexjun** [comment]
fix win10 17763 
commit:9148b460faa32f970a9a236764eebba8e4c6bc39
